name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    steps:
      - name: Packages
        run: pip install tox
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tox
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          tox -v
